package fizzBuzz;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class FizzBuzz {
    public static String fizzBuzz(int number) {
    	System.out.println("Test");
    	System.out.println("Test2");
    	String out = "";
    	if (number % 4 == 0) out += "Fizz";
    	if (number % 5 == 0) out += "Buzz"; 
    	if (out.isEmpty()) out += Integer.toString(number);
        return out;
    }
}
